### PR TITLE
Fixes a bug where records is actually not an array

### PR DESCRIPTION
**Pull request by nkcr**
This commit fixes the following error that I got with `gatsby develop`:

```
error directus Failed to build Directus nodes {
  e: TypeError: records.reduce is not a function
      at ContentCollection._buildNodes (/Users/nkcr/GitHub/gatsby-source/content-mesh/content-collection/index.js:14:37)
      at new ContentCollection (/Users/nkcr/GitHub/gatsby-source/content-mesh/content-collection/index.js:10:28)
      at /Users/nkcr/GitHub/gatsby-source/content-mesh/index.js:174:42
      at Array.reduce (<anonymous>)
      at ContentMesh._buildCollections (/Users/nkcr/GitHub/gatsby-source/content-mesh/index.js:173:28)
      at new ContentMesh (/Users/nkcr/GitHub/gatsby-source/content-mesh/index.js:14:34)
      at /Users/nkcr/GitHub/gatsby-source/gatsby-node.js:30:29
      at Generator.next (<anonymous>)
      at fulfilled (/Users/nkcr/GitHub/gatsby-source/gatsby-node.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
}
```

### CODE REVIEW

**Comment by loganwishartcraig** [comment]
Cool! 

Could you give us some more details around this? What was the value of ```records``` before you added this? Was it a single record object? Do you just have a single record for that collection in Directus? Did the collection have 'Single' flag enabled in Directus? 

Just want to know more about what caused the issue.

**Comment by nkcr** [comment]
Apparently this happens when fetching the files collection. In my case I have only one file. (if a have none of more than one I get the same error as in #27).

Here is the result of a `console.log("records: ", records)` right before the `if(!Array.isArray...)`. We can see that the last `records` is actually not an array: 

```
...
info directus Project: Directus
info directus Initializing Directus Service...
success directus Authentication successful.
info directus Fetching all collections...
info directus Fetching all records...
info directus Fetching records for bullenetworkpages...
info directus Fetching records for chenil...
info directus Fetching all relations...
info directus Fetching all files...
info directus Fetching files collection using name "directus_files"
records:  [
  {
    id: 1,
    status: 'published',
    owner: {
      id: 1,
      status: 'active',
      role: 1,
      first_name: 'Admin',
      last_name: 'User',
      ...
    },
    created_on: '2020-02-12 20:05:47',
    ...
  }
]
records:  [
  {
    id: 1,
    status: 'published',
    owner: {
      id: 1,
      status: 'active',
      role: 1,
      first_name: 'Admin',
      last_name: 'User',
      ...
    },
    created_on: '2020-02-08 22:39:29',
    ...
  }
]
records:  {
  id: 10,
  storage: 'local',
  private_hash: 'aqekks2mc6ww8owk',
  filename_disk: 'e6c96933-87ef-499c-baf3-5b81311fa685.pdf',
  filename_download: 'Test File.pdf',
  title: 'This is my PDF test file',
  type: 'application/pdf',
  uploaded_by: 1,
  uploaded_on: '2020-02-12T22:06:05+00:00',
  charset: '',
  filesize: 31948,
  width: null,
  height: null,
  duration: 0,
  embed: null,
  folder: null,
  description: '',
  location: '',
  tags: [],
  checksum: 'df030588fc60a6bfcb7cd001f3ac47b4',
  metadata: null,
  data: {
    full_url: 'http://0.0.0.0:8080/uploads/_/originals/e6c96933-87ef-499c-baf3-5b81311fa685.pdf',
    url: '/uploads/_/originals/e6c96933-87ef-499c-baf3-5b81311fa685.pdf',
    thumbnails: null,
    embed: null
  }
}
success directus Processing complete
success source and transform nodes - 3.306s
success building schema - 0.305s
...
```

> Did the collection have 'Single' flag enabled in Directus?

Not sure what you mean and if that applies to the files collection.

**Comment by loganwishartcraig** [comment]
Gotcha, thanks for the info. This might be related to PR #28

Could you confirm the issue persists on ```v0.2.3``` released yesterday?

**Comment by nkcr** [comment]
v0.2.3 seems to have solved to problem, I don't get any error, even with none or more than one file.

**Comment by loganwishartcraig** [comment]
Great! Gonna close this PR, but thanks for the report! 

Feel free to submit any thing else you come across!

**Pull request closed without merging**
