### PR TITLE
add limit "-1" in getCollectionRecords

### LINKED ISSUE #35: Paging and large collections
Hey guys. Great work with all this.
I have a use case that involves thousands of records whilst directus will return a max of 300 for any get_items call by default. Limitless searches require a -1 in the limit query field, but I do understand this might not be the best strategy for the plugin.

For now im just using a modified version as I have to get this done asap.I include this change at the end for reference. 

However, i guess the most sensible thing would be to allow for a config entry, maybe per collection, to set the limit of records fetched (unless there is something in building the content mesh i still dont understand, which would be very very likely as im a total newb and I dont tscript at all).

If or when I have the time, ill try to make this work the right way and submit a patch. 

PS: Sorry if my ranting is just taking valuable time away from you... :/

```
public async getCollectionRecords(collection: string): Promise<any[]> {
    try {
      log.info(`Fetching records for ${collection}...`);

      const { data: items = [] } = (await this._api.getItems(collection, {
        fields: '*.*',
        limit:-1, //<------RIGHT HERE
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
      })) as { data: any[] };

      return items.filter(record => this._shouldIncludeRecord(record, collection));
    } catch (e) {
      log.error(`Failed to fetch records for collection "${collection}"`);
      log.error(`Did you grant READ permissions?`);
      throw e;
    }
  }
```

### PR DESCRIPTION
**Pull request by IgordeOliveira**
Fix #35

### CODE REVIEW

**Comment by jooola** [comment]
@loganwishartcraig Are we good with this hotfix ? The creation of a pagination system can be postponed, while some might need this fix relatively soon.

I'll leave you do the merging and releasing.

**Comment by loganwishartcraig** [comment]
Seems like a good hotfix! I'll just merge and provide the same config for the other requests (files, collections, relations).

Sorry for being so mia - hoping to get some time to implement some more tests and pagination this week

Thanks @IgordeOliveira for the PR!

**Comment by loganwishartcraig** [comment]
For clarity, other SDK calls were updated to include ```limit: -1``` in commit f43fc6e

**Comment by jooola** [comment]
@loganwishartcraig No pressure, we do this on our free time. Our response time is actually quite good !

**Pull request merged**
