### PR TITLE
Split README into documentation

### LINKED ISSUE #32: Enhance documentation, reduce README size
I propose to move the code samples, and any advanced documentation in a /docs folder with smaller files. I feel like having everything in the `README` is really not easy to read/manage.

We need to structure the docs a bit more, so that it is browsable for those who seek for advanced configuration sample.

I might move the release documentation in its own file. So if newcomers search the docs it will be easy to find it with a `RELEASE.md` filename.

Maybe even build a small website that render our documentation (vuepress ?) using github pages, but we will need @rijkvanzanten approval and github page setup if we do this.
@loganwishartcraig Any thoughts ?

### PR DESCRIPTION
**Pull request by jooola**
Fixes #32

### CODE REVIEW

**Comment by jooola** [comment]
@loganwishartcraig Could you please browse the documentation in the documentation branch and tell me whether the changes are ok for you ?
https://github.com/directus/gatsby-source/tree/documentation#documentation

**Comment by jooola** [comment]
We might need to create a proper table of content in README.md

**Comment by loganwishartcraig** [comment]
Hey! Definitely like it split out more, I think this is great!

I added an ```Authentication``` section to consolidate that info. I also made some minor cosmetic changes.

Let me know what you think!

**Comment by jooola** [comment]
Options types were in Js style because:
- I wanted the Js syntax highlighting to work on Github (yeah not really a problem actually, but docs with color is always better).
- Js seems more universal since typescript supersedes it only, and most Gatsby users will use Js. I haven't seen any ts project yet, but I'll be interested in seeing one !
- But, I agree typing wasn't really consistent, I was mixing ts and js.

That said I really don't mind the change, feel free to revert if you change your mind. 

I wonder if the README table of content will work on the gatsby plugin page. We might need to fix this ?

**Comment by jooola** [comment]
I feel like this one is ready to go, apart from the gatsby.  What do you think ?

Should we merge and release ?

**Comment by jooola** [comment]
@loganwishartcraig Could you please clean up/clone the project again, we have a buggy submodule leftover, and you are pushing it really often to the repository.

**Comment by loganwishartcraig** [comment]
Ah, your reasoning makes for using ```String``` ```Boolean``` etc makes sense. I just looked at a couple other ```gatsby-source``` plugins. Most don't mention types explicitly, but those I saw that did use all lower case. I'm with you though, I don't mind either way really! The syntax highlighting is nice.

> I wonder if the README table of content will work on the gatsby plugin page. We might need to fix this ?

Are you concerned about the relative links like ```#documentation```? [This project](https://github.com/sanity-io/gatsby-source-sanity) uses them in their README and it seems okay on the Gatsby site [here](https://www.gatsbyjs.org/packages/gatsby-source-sanity/?=gatsby-source)

> @loganwishartcraig Could you please clean up/clone the project again, we have a buggy submodule leftover, and you are pushing it really often to the repository.

Definitely - my bad, wasn't aware of this :s

**Comment by loganwishartcraig** [comment]
I think this would be fine to merge.

**Comment by jooola** [comment]
I was concerned about links between the README and the documentation.
The readme will be exposed on the npm and gatsby plugin browser and we need to be able to link to github. But I added absolute links to the documentation file, it should work just fine.

**Pull request merged**
