### PR TITLE
Start testing the project

### LINKED ISSUE #2: Write tests
This plugin need to be fully tested in order to make the development easy. A Directus backend will be required to perform basic calls on it.

### PR DESCRIPTION
**Pull request by jooola**
This PR ships some tools used to test this project.

It still needs some cleanup and real tests, but the idea is here.

This work could alse be used to run e2e tests for the API project @WoLfulus @rijkvanzanten.

Fixes #2

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Do you wanna merge this in first and then continue on to filling in the blanks for the tests, or finish the tests first @jooola?

**Comment by jooola** [comment]
@rijkvanzanten Let's build the e2e tests first then we can merge.

**Comment by jooola** [comment]
@loganwishartcraig What do you think about @rijkvanzanten question ? Should we merge this and continue building tests on another branch ? Or are you open for contributing to this branch ?

**Comment by loganwishartcraig** [comment]
@jooola 

I'm cool just pushing test cases to this branch if that's easier. Do you have a strong opinion either way?
Have been working to setup my test env, but have yet to build out any test cases.

**Comment by loganwishartcraig** [comment]
@jooola Finally got my test env up haha.

The single test we have is working for me. I will try to find some time to finally write some basic tests haha. We should add some more data to the demo instance - would be good to test o2m/m2m/file/files relations as that's probably the most complex part of the plugin!

**Comment by jooola** [comment]
The tests cannot pass on Github because the Directus server isn't ready at the time of the tests. I suspect the size of the demo-data that needs to be initialized.

Also Server ping should respond only when ready. This could be a way to wait until the server is really ready.

I would propose to use our own set of data so we can change what we needs instead of relying on the huge demo-data repository. And as you said, we need some M2M/O2M relations for some testing.

**Comment by loganwishartcraig** [comment]
@jooola What do you think about forking the ```demo-data``` repo and building out some M2M/O2M relations using that data set as a base?

**Comment by jooola** [comment]
@loganwishartcraig Like I said above, I feel like the demo data set is too big and isn't loaded quickly enough in the CI (I might have some other bug also but that has something todo with DNS and the directus hostname not found on the ci network).

Yes, I would agree on building our own set of data or to fork and reduce the size of the demo-data.

**Comment by jooola** [comment]
@loganwishartcraig Ok, this one has taken me way too much time, but I'm glad I pulled this off. It will be usable for other SDKs. :tada: :rocket:

So testing will always be done against a docker-compose setup (sorry for the hard dependency on docker), either locally or in the CI.

I'll split tests in 2 categories, e2e test that require the docker environment and unit testing that can be run without it.

Let me document this quickly and I'll merge this.

**Pull request merged**
